#!/bin/sh
# Получаем сообщение последнего коммита
COMMIT_MSG=$(git log -1 --pretty=%B)

# Запускаем Node.js скрипт
node generateUpdates.cjs "$COMMIT_MSG"

# Добавляем src/updates.jsx в индекс
git add src/updates.jsx
